### ISSUE TITLE
Ask a question

### ISSUE THREAD

**Issue by xiaozhuxiong121** [ooper-shlab/iPhoneACFileConvertTest-Swift#1]
`OutputAAC .caf` change to `OutputAAC .aac` can not play, why

**Comment by ooper-shlab** [comment]
Please clarify your question. I do not understand what you have done or what you are trying.

**Comment by xiaozhuxiong121** [comment]
I want to convert pcm files to aac files
E.g
demo `sourcePCM.aif` converted into `sourcePCM.aac` Is that OK？
Or is there any other way?

**Comment by ooper-shlab** [comment]
If your actual purpose is to convert the file formats of existing audio files into other file formats, try `afconvert` command of your Mac. You can find many articles searching with "how to use afconvert". This sample code converts the internal data formats of audio files in CAF file format, it does not convert the file formats.
